version: '2'
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:management
  flower:
    image: mher/flower
    command: --broker amqp://guest@rabbitmq/ --url-prefix=manage/flower
    depends_on:
      - celery
  init:
    image: facerec/dev:latest
    command: facerec-ctl init dev
    volumes:
      - .:/facerec:rw
      - media:/data/media:rw
      - cache:/data/cache:rw
      - static:/facerec/project/static:rw
  celery:
    extends: init
    command: facerec-ctl celery
    tty: true
  uwsgi:
    extends: init
    command: facerec-ctl uwsgi
    expose:
      - 8000
  nginx:
    image: ngnix
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/srv/www/:ro
      - ui-dist:/srv/www/app/:ro
    ports:
      - 127.0.0.1:8000:80
volumes:
  media: {}
  cache: {}
  static: {}
