version: '2'
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:management
  flower:
    image: mher/flower
    command: --broker amqp://guest@rabbitmq/ --url-prefix=manage/flower
    depends_on:
      - celery
  init:
    image: producer/dev:cv3.3
    command: facerec-ctl init dev
    volumes:
      - .:/facerec:rw
      - media:/data/media:rw
      - cache:/data/cache:rw
      - static:/facerec/project/static:rw
      - ./project/db:/data/db:rw
      #- /media/lebowski/Maxtor1/thesis_video/:/thesis_video:rw
      - /home/yiorgos/Downloads/:/local/Dowloads:rw
  celery:
    extends: init
    command: facerec-ctl celery
    tty: true
  uwsgi:
    extends: init
    command: facerec-ctl uwsgi
    expose:
      - 8000
  nginx:
    image: local_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/srv/www/:ro
    ports:
      - 127.0.0.1:8000:80
volumes:
  media: {}
  cache: {}
  static: {}
