# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cascade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('xml_file', models.FileField(upload_to='haar_cascades/')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cascade_name', models.CharField(max_length=50)),
                ('cascade_scale', models.CharField(max_length=50)),
                ('cascade_neighbors', models.CharField(max_length=50)),
                ('cascade_min_face_size', models.CharField(max_length=50)),
                ('cascade_boxes', models.CharField(max_length=50)),
                ('recognizer_name', models.CharField(max_length=50)),
                ('objdetector_name', models.CharField(max_length=50)),
                ('manual_tags', models.CharField(max_length=50)),
            ],
        ),
    ]
