# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aat', '0002_recognizerpretraineddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizerpretraineddata',
            name='csv_path',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recognizerpretraineddata',
            name='faces_path',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
