# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aat', '0003_auto_20170914_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
