# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aat', '0005_auto_20171129_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizerpretraineddata',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
